version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: imc-policy-postgres
    environment:
      POSTGRES_DB: imc_policy
      POSTGRES_USER: imc_user
      POSTGRES_PASSWORD: imc_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imc_user -d imc_policy"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: